import { BlurText } from '../components/BlurText';
import { CtaFooter } from '../components/CtaFooter';
import { Zap, Palette, BarChart3, Shield, Globe, Smartphone } from 'lucide-react';

export function Services() {
  const services = [
    {
      icon: <Globe className="w-6 h-6 text-white" />,
      title: "AI Web Design",
      description: "Custom, high-converting websites generated by AI and refined by top-tier designers. We blend data-driven layouts with stunning aesthetics."
    },
    {
      icon: <Smartphone className="w-6 h-6 text-white" />,
      title: "Mobile Optimization",
      description: "Flawless experiences across all devices. We ensure your site looks and performs beautifully on smartphones and tablets."
    },
    {
      icon: <Zap className="w-6 h-6 text-white" />,
      title: "Performance Tuning",
      description: "Lightning-fast load times. We optimize every asset, script, and server response to keep your bounce rates near zero."
    },
    {
      icon: <BarChart3 className="w-6 h-6 text-white" />,
      title: "Conversion Strategy",
      description: "Layouts informed by data. We analyze user behavior to place CTAs and content exactly where they drive the most action."
    },
    {
      icon: <Palette className="w-6 h-6 text-white" />,
      title: "Brand Identity",
      description: "More than just a logo. We build cohesive visual systems that communicate your brand's unique value and premium positioning."
    },
    {
      icon: <Shield className="w-6 h-6 text-white" />,
      title: "Enterprise Security",
      description: "Bank-grade protection for your digital assets. SSL, DDoS mitigation, and continuous monitoring come standard."
    }
  ];

  return (
    <div className="bg-black min-h-screen pt-24 md:pt-32">
      <div className="max-w-7xl mx-auto px-4 md:px-12 lg:px-24 py-16 md:py-24">
        <div className="flex flex-col items-center text-center mb-12 md:mb-20">
          <div className="liquid-glass rounded-full px-3.5 py-1 text-[10px] md:text-xs font-medium text-white font-body mb-4 md:mb-6">
            Our Expertise
          </div>
          <BlurText 
            text="Services built for scale." 
            className="text-4xl sm:text-5xl md:text-7xl font-heading italic text-white mb-4 md:mb-6 justify-center" 
          />
          <p className="text-white/60 max-w-2xl text-sm md:text-lg font-body font-light px-2">
            We don't just build websites. We engineer digital experiences designed to dominate your market and convert visitors into loyal customers.
          </p>
        </div>

        <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-4 md:gap-6 mb-16 md:mb-24">
          {services.map((service, i) => (
            <div key={i} className="liquid-glass rounded-2xl p-6 md:p-8 flex flex-col items-start text-left hover:bg-white/5 transition-colors duration-300">
              <div className="liquid-glass-strong rounded-full w-10 h-10 md:w-12 md:h-12 flex items-center justify-center mb-5 md:mb-6">
                {service.icon}
              </div>
              <h3 className="text-xl md:text-2xl font-heading italic text-white mb-3 md:mb-4">
                {service.title}
              </h3>
              <p className="text-white/60 font-body font-light text-xs md:text-sm leading-relaxed">
                {service.description}
              </p>
            </div>
          ))}
        </div>
      </div>
      <CtaFooter />
    </div>
  );
}
